### ISSUE TITLE
Warning & then errors during first, and subsequent runs

### ISSUE THREAD

**Issue by pboling** [wangyucode/sftp-upload-action#1]
It is working great, but I see a warning during the run:

```
(node:1871) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

Perhaps this has been fixed upstream in the Node project?

**Comment by pboling** [comment]
Turns out it only worked for the very first deploy.  The second deploy hung, and I had to cancel it.

The next deploy that ran I got an error:
```
      file uploaded : sanitize_email/intro/index.html
     sync completed : sanitize_email/intro
sftp upload error!  OperationalError: Failure
    at SFTPStream._transform (/home/runner/work/_actions/wangyucode/sftp-upload-action/v1.1/dist/index.js:19485:27)
Error: Failure
    at SFTPStream.Transform._read (_stream_transform.js:189:10)
    at SFTPStream._read (/home/runner/work/_actions/wangyucode/sftp-upload-action/v1.1/dist/index.js:19256:15)
    at SFTPStream.Transform._write (_stream_transform.js:177:12)
    at doWrite (_stream_writable.js:431:12)
    at writeOrBuffer (_stream_writable.js:415:5)
    at SFTPStream.Writable.write (_stream_writable.js:305:11)
    at Channel.ondata (_stream_readable.js:727:22)
    at Channel.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Channel.Readable.push (_stream_readable.js:224:10)
    at SSH2Stream.<anonymous> (/home/runner/work/_actions/wangyucode/sftp-upload-action/v1.1/dist/index.js:28449:15)
    at SSH2Stream.emit (events.js:210:5)
    at parsePacket (/home/runner/work/_actions/wangyucode/sftp-upload-action/v1.1/dist/index.js:25493:10)
    at SSH2Stream._transform (/home/runner/work/_actions/wangyucode/sftp-upload-action/v1.1/dist/index.js:22718:13) {
  cause: Error: Failure
      at SFTPStream._transform (/home/runner/work/_actions/wangyucode/sftp-upload-action/v1.1/dist/index.js:19485:27)
      at SFTPStream.Transform._read (_stream_transform.js:189:10)
      at SFTPStream._read (/home/runner/work/_actions/wangyucode/sftp-upload-action/v1.1/dist/index.js:19256:15)
      at SFTPStream.Transform._write (_stream_transform.js:177:12)
      at doWrite (_stream_writable.js:431:12)
      at writeOrBuffer (_stream_writable.js:415:5)
      at SFTPStream.Writable.write (_stream_writable.js:305:11)
      at Channel.ondata (_stream_readable.js:727:22)
      at Channel.emit (events.js:210:5)
      at addChunk (_stream_readable.js:309:12)
      at readableAddChunk (_stream_readable.js:290:11)
      at Channel.Readable.push (_stream_readable.js:224:10)
      at SSH2Stream.<anonymous> (/home/runner/work/_actions/wangyucode/sftp-upload-action/v1.1/dist/index.js:28449:15)
      at SSH2Stream.emit (events.js:210:5)
      at parsePacket (/home/runner/work/_actions/wangyucode/sftp-upload-action/v1.1/dist/index.js:25493:10)
      at SSH2Stream._transform (/home/runner/work/_actions/wangyucode/sftp-upload-action/v1.1/dist/index.js:22718:13) {
    code: 4,
    lang: ''
  },
  isOperational: true,
  code: 4,
  lang: ''
}
```

You can see it here https://github.com/pboling/railsbling.com/runs/3924133474?check_suite_focus=true

**Comment by Lionad-Morotar** [comment]
我遇到了同样的问题... :(
