### ISSUE TITLE
More informations in when can't make SFTP connection

### ISSUE THREAD

**Issue by Elikill58** [wangyucode/sftp-upload-action#34]
I have  this log:
```
Error: connect: getConnection: All configured authentication methods failed
    at SftpClient.fmtError (/home/runner/work/_actions/wangyucode/sftp-upload-action/v2.0.2/dist/index.js:7737:***)
    at SftpClient.connect (/home/runner/work/_actions/wangyucode/sftp-upload-action/v2.0.2/dist/index.js:7875:37)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Deployer.sync (/home/runner/work/_actions/wangyucode/sftp-upload-action/v2.0.2/dist/index.js:37:9) {
  code: 'ERR_GENERIC_CLIENT',
  custom: true
}
can not read remote folder -> /home/myFolder
found 0 remote files
creating file -> /home/myFolder/Project.jar
/home/runner/work/_actions/wangyucode/sftp-upload-action/v2.0.2/dist/index.js:7737
    const newError = new Error(msg);
                     ^
Error: mkdir: mkdir: No SFTP connection available
    at SftpClient.fmtError (/home/runner/work/_actions/wangyucode/sftp-upload-action/v2.0.2/dist/index.js:7737:***)
    at SftpClient.mkdir (/home/runner/work/_actions/wangyucode/sftp-upload-action/v2.0.2/dist/index.js:8524:18)
    at Deployer.upload (/home/runner/work/_actions/wangyucode/sftp-upload-action/v2.0.2/dist/index.js:87:41)
    at Deployer.sync (/home/runner/work/_actions/wangyucode/sftp-upload-action/v2.0.2/dist/index.js:42:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_NOT_CONNECTED',
  custom: true
}
```
I checked for connection, and everything were working. I'm now logged in SFTP thanks to WinSCP with same informations as given to github actions.

The issue is the error don't give useful information, and only say it can't connect.

Can you change it?

**Comment by wangyucode** [comment]
This might be because you are using an incorrect username to log in.
The error message `"All configured authentication methods failed"` was logged by the `ssh2-sftp-client` library.
However, I have improved the logic in `2.0.3`, so if the connection fails, the process will stop and there will be no further confusion.
